### ISSUE TITLE
Make Datadog "Site" e.g. datadoghq.eu configurable

### ISSUE THREAD

**Issue by schwamster** [KyleRoss/node-datadog-events#1]
thx for the this package. It nicely wraps what I need from the API. One thing that I would like to be able to configure is the Datadog Site. Since the end of last year users can choose to have their data stored in the European datadog site -> datadoghq.eu [see press release]( https://www.businesswire.com/news/home/20181018005040/en/Datadog-Launches-EU-Region-Germany)

To use that site through the api, one has to change the base URL. So instead of https://app.datadoghq.com/api/v1 it would be https://app.datadoghq.eu/api/v1

I would like this to be configurable with "datadoghq.com" as a default. I will gladly provide a PR if this aligns with your ideas for this repo.

**Comment by KyleRoss** [comment]
@schwamster Thanks for submitting this, I agree this option needs to be added to the package. After looking at your PR, I'm trying to determine if there is a better way to handle the switch. I'm going to dive into this now.

**Comment by KyleRoss** [comment]
@schwamster Changes have been made and published to NPM as version 1.1.0.

Thanks for reporting, I appreciate it!
